### ISSUE TITLE
error - assets directory doesn't exist

### ISSUE THREAD

**Issue by joetwostep** [2amigos/yii2-leaflet-geosearch-plugin#5]
I just installed and tried to run the sample code in the readme file with the geosearch plugin, ad get this error: "The file or directory to be published does not exist: /var/www/html/yii-advanced-app/vendor/2amigos/yii2-leaflet-geosearch-plugin/assets"  I looked and the $sourcePath in GeoSearchAsset.php looks wrong, I had to change it from '@vendor/2amigos/yii2-leaflet-geosearch-plugin/assets' to '@vendor/2amigos/yii2-leaflet-geosearch-plugin/src/assets' and now it works.  Surprised I would get such a basic error for this tool which has been around for a while, does anyone use this?

**Comment by ScottHuangZL** [comment]
I do the same thing. I think it should be he change source code but did not publish to packgist

**Comment by tonydspaniard** [comment]
@joetwostep @ScottHuangZL apologies. Is all done and works now. new tag version added. 

we are just so busy that i couldn't even check the repositories of our open source. my bad.
