### ISSUE TITLE
Demo urlTemplate issues

### ISSUE THREAD

**Issue by robwent** [2amigos/yii2-leaflet-geosearch-plugin#6]
Following the demo code, I got no map tiles and a console error that {s} isn't defined.

I went through some issues on the leaflet repo and found that if I changed the tiles url to the following then the map started working.

    'urlTemplate' => 'https://a.tile.openstreetmap.org/{z}/{x}/{y}.png',

**Comment by tonydspaniard** [comment]
Yes, you are right, they do not work... would be nice if you could do a PR for that change... do you have time?
